theme: jekyll-theme-cayman
title: Classification of Low Humidity Days in San Diego, CA
description: Based on assignments from Big Data Specialization by University of California San Diego on Coursera
